import Head from "next/head";
import React, { ReactChild } from "react";

interface LayoutProps {
  children: ReactChild[];
}

export default function Layout(props: LayoutProps) {
  return (
    <div className="font-mons">
      <Head>
        <title>Beauty That's Moves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>
      </Head>
      {props.children}
    </div>
  );
}
